sudo: required

language: python

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

services:
  - docker

install:
  - touch local.env
  - env >> local.env
  - docker-compose build
  - docker-compose run web python manage.py collectstatic --noinput
  - docker-compose run web python manage.py makemigrations --noinput

script:
  - docker-compose run web py.test

notifications:
  email:
    on_success: change
    on_failure: change

