db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: "supersecret"
    POSTGRES_USER: "user"
    POSTGRES_DB: "podato"
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    POSTGRES_PASSWORD: "supersecret"
    POSTGRES_USER: "user"
    POSTGRES_DB: "podato"
    POSTGRES_HOST: "db"
    SECRET_KEY: "(mz8cry@72_x0bl3mi$$r*5us2js5@lnv^)e@fw+7l6x@$q8y3"
    DEBUG: "1"