# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('enclosure_type', models.CharField(max_length=20)),
                ('enclosure_url', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('explicit', models.SmallIntegerField(choices=[(-1, 'not set'), (0, 'clean'), (1, 'explicit')])),
                ('author', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('explicit', models.SmallIntegerField(choices=[(-1, 'not set'), (0, 'clean'), (1, 'explicit')], default=-1)),
                ('owner_email', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=255)),
                ('last_fetched', models.DateTimeField()),
                ('categories', models.ManyToManyField(to='podcasts.Category')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
