# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('parent_name', models.CharField(blank=True, max_length=40)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('guid', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('enclosure_type', models.CharField(max_length=20)),
                ('enclosure_url', models.URLField(max_length=255)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('explicit', models.CharField(choices=[('u', 'not set'), ('c', 'clean'), ('e', 'explicit')], default='u', max_length=1)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('published', models.DateTimeField()),
                ('warnings', utils.fields.SeparatedValuesField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('copyright', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(blank=True, max_length=255, null=True)),
                ('explicit', models.CharField(choices=[('u', 'not set'), ('c', 'clean'), ('e', 'explicit')], default='u', max_length=1)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', utils.fields.SeparatedValuesField(blank=True, max_length=200, null=True)),
                ('last_fetched', models.DateTimeField()),
                ('warnings', utils.fields.SeparatedValuesField(blank=True, max_length=200, null=True)),
                ('categories', models.ManyToManyField(to='podcasts.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed', models.DateTimeField(auto_now_add=True, help_text='The date on which the user subscribed to this podcast')),
                ('unsubscribed', models.DateTimeField(help_text='The date on which the user unsubscribed from this podcast.')),
                ('podcast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='podcasts.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'parent_name')]),
        ),
    ]
