# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
