# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 14:15
from __future__ import unicode_literals

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcast_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='warnings',
            field=utils.fields.SeparatedValuesField(blank=True, max_length=200, null=True),
        ),
    ]
