# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_auto_20160213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.Podcast'),
        ),
    ]
