# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_auto_20160215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='podcasts.Podcast'),
        ),
    ]
