# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0006_auto_20160215_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(through='podcasts.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
