# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_podcast_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='unsubscribed',
        ),
        migrations.AlterField(
            model_name='episode',
            name='author',
            field=models.CharField(blank=True, help_text='The author of this episode.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='content',
            field=models.TextField(blank=True, help_text='Content of the post (from RSS feed).', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the episode', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='The duration of this episode;'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='enclosure_type',
            field=models.CharField(help_text='The type of file this episode is.', max_length=20),
        ),
        migrations.AlterField(
            model_name='episode',
            name='enclosure_url',
            field=models.URLField(help_text='The url of the file for this episode.', max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='explicit',
            field=models.CharField(choices=[('u', 'not set'), ('c', 'clean'), ('e', 'explicit')], default='u', help_text='Whether this episode contains explicit content.', max_length=1),
        ),
        migrations.AlterField(
            model_name='episode',
            name='guid',
            field=models.CharField(help_text="The episode's unique identifier.", max_length=400, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.URLField(blank=True, help_text='The image associated with this episode.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.URLField(help_text='A web link to the episode.', max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(help_text='The podcast this episode belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.Podcast'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published',
            field=models.DateTimeField(help_text='The moment this episode was published.'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='subtitle',
            field=models.CharField(blank=True, help_text='The episode subtitle.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.CharField(blank=True, help_text='A summary of the episode.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(help_text='The episode title.', max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='warnings',
            field=utils.fields.SeparatedValuesField(blank=True, help_text='Any warnings generated while fetching.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, help_text="The podcast's author.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=models.ManyToManyField(help_text='Tags that describe the podcast.', to='podcasts.Category'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='copyright',
            field=models.CharField(blank=True, help_text="A podcast's copyright statement.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(help_text="The podcast's description."),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='explicit',
            field=models.CharField(choices=[('u', 'not set'), ('c', 'clean'), ('e', 'explicit')], default='u', help_text='Whether the podcast contains explicit content.', max_length=1),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.URLField(blank=True, help_text='The url of an image for the podcast.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='language',
            field=models.CharField(blank=True, help_text='The language the podcast is in.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_fetched',
            field=models.DateTimeField(help_text='When the podcast feed was last fetched.'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='link',
            field=models.CharField(help_text="A link to the podcast's website.", max_length=255),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='owner_email',
            field=models.CharField(blank=True, help_text="The email of the podcast's owner.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='owner_name',
            field=models.CharField(blank=True, help_text="The podcast owner's name.", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(help_text='The users who subscribe to this podcast.', related_name='subscriptions', through='podcasts.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='tags',
            field=utils.fields.SeparatedValuesField(blank=True, help_text='Podcast tags.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(help_text="The podcast's title.", max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.CharField(help_text="The podcast's feed url.", max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='warnings',
            field=utils.fields.SeparatedValuesField(blank=True, help_text='Any warnings generated while fetching.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_objs', to=settings.AUTH_USER_MODEL),
        ),
    ]
