# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0008_auto_20160224_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The moment the comment was created.')),
                ('body', models.TextField(help_text="The comment's body text")),
                ('time_in_episode', models.IntegerField(blank=True, help_text='The point in the episode when the comment was made', null=True)),
                ('author', models.ForeignKey(help_text='The user who left the comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(help_text='The episode the user is commenting on.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='podcasts.Episode')),
            ],
        ),
    ]
