# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcasts', '0009_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_objs', to='podcasts.Episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_recommendation_objs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_objs', to='podcasts.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_objs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='recommending_users',
            field=models.ManyToManyField(related_name='recommended_episodes', through='podcasts.EpisodeRecommendation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='recommending_users',
            field=models.ManyToManyField(related_name='recommended_podcasts', through='podcasts.PodcastRecommendation', to=settings.AUTH_USER_MODEL),
        ),
    ]
